[project]
name = "demo-voice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq>=0.22.0",
    "openai>=1.74.0",
    "streamlit>=1.44.1",
]
